### ISSUE TITLE
Demo no longer working

### ISSUE THREAD

**Issue by a-r-d** [ShyamRaj/react-stickky#2]
Hey @ShyamRaj your demo is no longer working:

http://embed.plnkr.co/XvIwT0cAhEFxRL3clq7D/

Also, the sticky header is flickering for us on the transition to mobile view :mushroom: :metal: 

Hope your new job is going well!

**Comment by ShyamRaj** [comment]
I'll check it out and fix it buddy

**Comment by a-r-d** [comment]
👍

**Comment by ShyamRaj** [comment]
Fixed it!
